### ISSUE TITLE
Android9.0模拟器运行报错.

### ISSUE THREAD

**Issue by MagicKim** [BosCattle/JMessage-Android#1]
```java
2019-08-05 14:45:11.079 3420-3420/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.china.epower.chat, PID: 3420
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/ActionBarActivity;
        at xiaofei.library.hermes.util.TypeUtils$1.<init>(TypeUtils.java:51)
        at xiaofei.library.hermes.util.TypeUtils.<clinit>(TypeUtils.java:48)
        at xiaofei.library.hermes.util.TypeUtils.validateClass(TypeUtils.java:278)
        at xiaofei.library.hermes.util.TypeCenter.register(TypeCenter.java:94)
        at xiaofei.library.hermes.Hermes.register(Hermes.java:71)
        at xiaofei.library.hermeseventbus.HermesEventBus.init(HermesEventBus.java:122)
        at tech.jiangtao.support.kit.SupportIM.initialize(SupportIM.java:122)
        at tech.jiangtao.support.ui.SupportUI.initialize(SupportUI.java:62)
        at tech.jiangtao.support.ui.SupportUI.initialize(SupportUI.java:41)
        at com.china.epower.chat.app.PowerApp.onCreate(PowerApp.java:35)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.ActionBarActivity" on path: DexPathList[[zip file "/data/app/com.china.epower.chat-doZA30oJR0sydco11CGxtw==/base.apk"],nativeLibraryDirectories=[/data/app/com.china.epower.chat-doZA30oJR0sydco11CGxtw==/lib/x86, /data/app/com.china.epower.chat-doZA30oJR0sydco11CGxtw==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at xiaofei.library.hermes.util.TypeUtils$1.<init>(TypeUtils.java:51) 
        at xiaofei.library.hermes.util.TypeUtils.<clinit>(TypeUtils.java:48) 
        at xiaofei.library.hermes.util.TypeUtils.validateClass(TypeUtils.java:278) 
        at xiaofei.library.hermes.util.TypeCenter.register(TypeCenter.java:94) 
        at xiaofei.library.hermes.Hermes.register(Hermes.java:71) 
        at xiaofei.library.hermeseventbus.HermesEventBus.init(HermesEventBus.java:122) 
        at tech.jiangtao.support.kit.SupportIM.initialize(SupportIM.java:122) 
        at tech.jiangtao.support.ui.SupportUI.initialize(SupportUI.java:62) 
        at tech.jiangtao.support.ui.SupportUI.initialize(SupportUI.java:41) 
        at com.china.epower.chat.app.PowerApp.onCreate(PowerApp.java:35) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-08-05 14:45:11.183 2451-2478/com.android.launcher3 E/droid.launcher: No package ID ff found for ID 0xffffffff.
2019-08-05 14:45:11.183 2451-2478/com.android.launcher3 E/IconLoader: Could not find icon drawable from resource
    android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
        at android.content.res.Resources.getDrawable(Resources.java:827)
        at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(IconLoader.java:118)
        at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(IconLoader.java:94)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(RecentsTaskLoader.java:325)
        at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(RecentsTaskLoadPlan.java:188)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(RecentsTaskLoader.java:173)
        at com.android.quickstep.RecentsModel.onTaskStackChangedBackground(RecentsModel.java:214)
        at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(TaskStackChangeListeners.java:80)
        at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
        at android.os.Binder.execTransact(Binder.java:731)
```

**Comment by Labradors** [comment]
@MagicKim The project is no longer maintained
